apiVersion: metrics.crossplane.io/v1alpha1
kind: ResourceStateMetrics
metadata:
  name: rsm
spec:
  parameters:
    namespace:
      name: resource-state-metrics
    rbac:
      allowedAPIGroups:
        - apiextensions.crossplane.io
        - metrics.crossplane.io
        - pkg.crossplane.io
        - aws.platform.upbound.io
        - eks.aws.m.upbound.io
    deployment:
      replicas: 1
      image:
        repository: xpkg.crossplane.io/crossplane-contrib/resource-state-metrics-server
        tag: v0.3.0
      podMetadata:
        labels:
          example-label: example-label-value
        annotations:
          example-annotation: example-annotation-value
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
    service:
      telemetryPort: 9998
      metricsPort: 9999
      type: ClusterIP
